/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kr.or.yi.gradle_mybatis_dev;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
